site: Vistawound - Mobile Wound Care
baseurl: ""
url: "https://vistawound.com"
title: Vistawound - Mobile Wound Care
# description: Streamline your workflow, boost productivity, and achieve exceptional results with our cutting-edge technology platform designed for modern businesses.
encoding: utf-8
markdown: kramdown
sass:
  style: compressed
  sass_dir: _sass
defaults:
  - scope:
      path: ""
    values:
      layout: default
permalink: /:title/
collections:
  posts:
    output: true
    permalink: /:title/
