site: Vistawound - Medical and Doctor
baseurl: "/vistawound" # this is important
url: "https://cees3.github.io" # your GitHub Pages root
title: Vistawound - Medical and Doctor
# description: Streamline your workflow, boost productivity, and achieve exceptional results with our cutting-edge technology platform designed for modern businesses.
encoding: utf-8
markdown: kramdown
sass:
  style: compressed
  sass_dir: _sass
defaults:
  - scope:
      path: ""
    values:
      layout: default
